name: DEV.to Posts To Markdown
description: Search for new DEV blog posts and raise a PR with the post converted to Jekyll Markdown Post
runs:
  using: docker
  image: Dockerfile
branding:
  icon: book-open
  color: white
